version: "3"
services:
  web:
    build: .
    container_name: express-server
    ports:
    - "3000:3000"
    env_file:
      - .env
    networks:
      - server-network
    depends_on:
      db:
        condition: service_healthy
  db:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
      - MONGO_INITDB_DATABASE=test
      - .db_data:/data/db
    networks:
      - server-network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh --quiet
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  server-network:

volumes:
  .db_data: